# vim: nospell
#
# Basic template to test with GHC=[7.8, 7.10, 8.0]. Caches the 'stack' build
# directory to speed subsequent compilations.
#
# https://docs.travis-ci.com/user/reference/overview/
#
language: minimal
dist: trusty
sudo: required  # more storage available on sudo-enabled instances

cache:
  directories:
    - $HOME/.stack/snapshots
    - $HOME/.local/bin
    - .stack-work/install

before_cache:
  - rm -rf $(stack path --local-install-root)/doc

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc
      - ubuntu-toolchain-r-test
    packages: &apt_packages
      - libgmp-dev
      - happy-1.19.5
      - alex-3.1.7

matrix:
  include:
    - env: GHC=8.6.1
      compiler: "GHC 8.6"

    - env: GHC=8.4.2
      compiler: "GHC 8.4"

    - env: GHC=8.2.2
      compiler: "GHC 8.2"

    - env: GHC=8.0.2
      compiler: "GHC 8.0"

    # - env: GHC=head CABAL=head
    #   compiler: "GHC HEAD"
    #   addons: { apt: { sources: [ *apt_sources ], packages: [ *apt_packages, ghc-head, cabal-install-head ] }}

  # allow_failures:
  #   - env: GHC=head CABAL=head

  fast_finish: true

before_install:
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - source .travis/install-stack.sh

install:
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - travis_retry travis_wait 60 stack build --only-dependencies --fast --no-terminal --no-haddock-deps --no-copy-bins

script:
  - travis_retry stack build --fast --no-terminal --haddock --no-haddock-deps

after_success:
  - source .travis/update-accelerate-buildbot.sh

